In [2]:
import pandas as pd
df=pd.read_csv("airline_delay_cause.csv")

In [3]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",136.0,7.0,5.95,0.00,...,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",91.0,16.0,7.38,0.00,...,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",19.0,2.0,0.13,0.00,...,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,14.0,7.26,0.76,...,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",181.0,19.0,13.84,0.00,...,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 318017 entries, 0 to 318016
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 318017 non-null  int64
 1   month                318017 non-null  int64
 2   carrier              318013 non-null  str
 3   carrier_name         318013 non-null  str
 4   airport              318014 non-null  str
 5   airport_name         318017 non-null  str
 6   arr_flights          317524 non-null  float64
 7   arr_del15            317285 non-null  float64
 8   carrier_ct           317525 non-null  float64
 9   weather_ct           317523 non-null  float64
 10  nas_ct               317529 non-null  float64
 11  security_ct          317529 non-null  float64
 12  late_aircraft_ct     317529 non-null  float64
 13  arr_cancelled        317529 non-null  float64
 14  arr_diverted         317527 non-null  float64
 15  arr_delay            317523 non-null  float64
 16  carrier_delay        317525 non-null  float64
 17  weather_delay        317529 non-null  float64
 18  nas_delay            317529 non-null  float64
 19  security_delay       317527 non-null  float64
 20  late_aircraft_delay  317529 non-null  float64
dtypes: float64(15), int64(2), str(4)
memory usage: 51.0 MB

In [5]:
df.shape

(318017, 21)

In [6]:
df.describe()

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,318017.000000,318017.000000,317524.000000,317285.000000,317525.000000,317523.000000,317529.000000,317529.000000,317529.000000,317529.000000,317527.000000,317523.000000,317525.000000,317529.000000,317529.000000,317527.000000,317529.000000
mean,2012.450957,6.497844,381.766670,72.905076,21.073149,2.616407,24.005228,0.179037,24.975734,7.207257,0.867674,4209.989113,1286.577224,220.567542,1099.516422,7.214845,1596.062993
std,5.678296,3.459423,1027.156722,198.936754,47.671580,9.968640,85.113757,0.844834,75.275223,37.216301,3.915772,12519.021012,3515.417309,861.521440,4636.475908,38.854685,4924.950687
min,2003.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-19.000000,0.000000,0.000000
25%,2007.000000,3.000000,59.000000,9.000000,3.000000,0.000000,1.680000,0.000000,1.640000,0.000000,0.000000,436.000000,148.000000,0.000000,56.000000,0.000000,79.000000
50%,2012.000000,6.000000,120.000000,23.000000,8.190000,0.580000,5.490000,0.000000,5.860000,1.000000,0.000000,1201.000000,437.000000,25.000000,203.000000,0.000000,351.000000
75%,2018.000000,10.000000,273.000000,56.000000,19.690000,2.000000,15.350000,0.000000,17.040000,4.000000,1.000000,3080.000000,1100.000000,159.000000,602.000000,0.000000,1110.000000
max,2022.000000,12.000000,21977.000000,6377.000000,1792.070000,717.940000,4091.270000,80.560000,1885.470000,4951.000000,256.000000,433687.000000,196944.000000,57707.000000,238440.000000,3760.000000,148181.000000

In [7]:
df.isnull().sum()

year                     0
month                    0
carrier                  4
carrier_name             4
airport                  3
airport_name             0
arr_flights            493
arr_del15              732
carrier_ct             492
weather_ct             494
nas_ct                 488
security_ct            488
late_aircraft_ct       488
arr_cancelled          488
arr_diverted           490
arr_delay              494
carrier_delay          492
weather_delay          488
nas_delay              488
security_delay         490
late_aircraft_delay    488
dtype: int64

In [8]:
df=df.dropna()

In [9]:
df=df.drop_duplicates()

In [10]:
df.columns

Index(['year', 'month', 'carrier', 'carrier_name', 'airport', 'airport_name',
       'arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay'],
      dtype='str')

In [11]:
df.columns = df.columns.str.lower().str.strip()

In [12]:
df = df.dropna(subset=['arr_delay', 'arr_flights'])

In [13]:
df['year'] = df['year'].astype(int)
df['month'] = df['month'].astype(int)

In [14]:
dim_carrier = df[['carrier', 'carrier_name']].drop_duplicates()
dim_airport = df[['airport', 'airport_name']].drop_duplicates()

fact_flights = df.drop(columns=['carrier_name', 'airport_name'])

In [15]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://@localhost/SQLEXPRESS/airline_db?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [16]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client 11.0', 'SQL Server Native Client RDA 11.0', 'Oracle in OraDB21Home1', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server']

In [17]:
engine = create_engine(
    "mssql+pyodbc://@localhost\\SQLEXPRESS/airline_db?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [18]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mssql+pyodbc://@localhost\\SQLEXPRESS/airline_db?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).fetchall())

[(1,)]

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("airline_delay_cause.csv")

In [21]:
fact_flights = df[[
    'year','month','carrier','airport',
    'arr_flights','arr_delay',
    'carrier_delay','weather_delay',
    'nas_delay','security_delay','late_aircraft_delay'
]]

dim_carrier = df[['carrier','carrier_name']].drop_duplicates()
dim_airport = df[['airport','airport_name']].drop_duplicates()

In [22]:
fact_flights.to_sql("fact_flights", engine, if_exists="replace", index=False)
dim_carrier.to_sql("dim_carrier", engine, if_exists="replace", index=False)
dim_airport.to_sql("dim_airport", engine, if_exists="replace", index=False)

423